### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by joshwtodd** [martijndierckx/homebridge-hydrawise#11]
[5/7/2020, 6:37:46 PM] [Hydrawise] TypeError: Cannot read property 'getCharacteristic' of undefined
    at new HydrawiseSprinkler (C:\Users\joshw\AppData\Roaming\npm\node_modules\homebridge-hydrawise\src\HydrawiseSprinkler.ts:62:17)
    at C:\Users\joshw\AppData\Roaming\npm\node_modules\homebridge-hydrawise\src\HydrawisePlatform.ts:90:30   at Array.map (<anonymous>)
    at C:\Users\joshw\AppData\Roaming\npm\node_modules\homebridge-hydrawise\src\HydrawisePlatform.ts:66:13   at processTicksAndRejections (internal/process/task_queues.js:97:5)

Thanks for your plug-in first of all, second any idea why I keep getting the error message above ? occurs on the frequency of the polling interval .

**Comment by martijndierckx** [comment]
Can you make sure you’re on the latest version of homebridge and the latest stable node version?
You can also try removing the hydrawise devices from the homebridge cache.

**Comment by joshwtodd** [comment]
Yes on latest versions of all software, I have reinstalled the plugin also.

1) I don't get it as soon as I install the plugin, only occurs after the first restart of homebridge
2) It has something to do with the last sprinkler in my system - I have 20 zones (is this too many)?  but homekit gives me an error on it and it doesn't show up on the accessory tab in homebridge UI, all other sprinkler zones work perfectly.

**Comment by martijndierckx** [comment]
Can you post the debug output of homebridge ("homebridge -D") together with the output of the [troubleshooting script](https://github.com/martijndierckx/homebridge-hydrawise/blob/master/troubleshooting/hydrawise-api.js). Please make sure you remove your API key and passwords from the output before posting.
