### ISSUE TITLE
Zones sit idle and then time out

### ISSUE THREAD

**Issue by storkpkp** [martijndierckx/homebridge-hydrawise#2]
The zones appear in Home app just fine, but they cannot be activated. They spin at idle when selected and then time out with no response.

**Comment by martijndierckx** [comment]
Can you tell me a bit more about your setup?

**Comment by storkpkp** [comment]
What details do you need from me?

I am running:

iOS 11.4
Homebridge 0.44.4
Homebridge-Hydrawise 0.3
OS X 10.12.6

I have the Hydrawise Pro-C6 Controller with 3 zones. The zones show up fine, but when I try to run one it just says updating for a long time, and then no response.

Marcus

**Comment by storkpkp** [comment]
Hey there, I now have it working after generating a new API key, but I keep getting this message in my terminal. 

Unhandled rejection RequestError: Error: connect ETIMEDOUT 107.22.252.238:443
    at new RequestError (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/request-promise/lib/errors.js:14:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/request-promise/lib/rp.js:60:25)
    at self.callback (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/request/request.js:185:22)
    at Request.emit (events.js:127:13)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:127:13)
    at TLSSocket.socketErrorListener (_http_client.js:394:9)
    at TLSSocket.emit (events.js:127:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by martijndierckx** [comment]
Have a look, I fixed an issue. I hope it's the same you have.

**Comment by martijndierckx** [comment]
Did it fix the problem?
