### ISSUE TITLE
AxiosError: Request failed with status code 429

### ISSUE THREAD

**Issue by Bodie2023** [martijndierckx/homebridge-hydrawise#36]
Hi there.
Until v3.0 I was operating under IP, now with v4.3 I switched to Cloud, but I am not able to start it. If I turn on Hydrawise from its native app, the change is written to both HB and HK/AH, but if I turn it on from HB or Apple Home, nothing happens except this listing.
Can you help me? Thanks for any advice.

[16/07/2023, 17:26:55] Homebridge v1.6.1 (HAP v0.11.1) (Hydrawise) is running on port 53045.
[16/07/2023, 17:26:56] [Hydrawise] AxiosError: Request failed with status code 429
    at settle (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/axios/lib/adapters/http.js:570:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.4.0',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://app.hydrawise.com/api/v1/customerdetails.php',
    params: { type: 'controllers', api_key: '6572-FD55-0D50-6846' },
    json: true,
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'app.hydrawise.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'app.hydrawise.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 36,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/1.4.0\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: app.hydrawise.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 429,
      statusMessage: 'Too Many Requests',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://app.hydrawise.com/api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'app.hydrawise.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://app.hydrawise.com/api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kEndCalled)]: true,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 429,
    statusText: 'Too Many Requests',
    headers: AxiosHeaders {
      date: 'Sun, 16 Jul 2023 15:26:55 GMT',
      'content-type': 'application/json; charset=utf-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      server: 'nginx'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [AxiosHeaders],
      method: 'get',
      url: 'https://app.hydrawise.com/api/v1/customerdetails.php',
      params: [Object],
      json: true,
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.4.0\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: app.hydrawise.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'app.hydrawise.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    data: 'Exceeded maximum number of requests. You cannot make more than 5 requests in any 5 minute period to this endpoint.'

OK, I put 12000 to Pooling interval, restart and:

16/07/2023, 18:04:07] [Hydrawise] Restarting Process...
[16/07/2023, 18:04:08] [Hydrawise] Launched child bridge with PID 14784
[16/07/2023, 18:04:08] Registering platform 'homebridge-hydrawise.HydrawisePlatform'
[16/07/2023, 18:04:08] [Hydrawise] Loaded homebridge-hydrawise v1.2.1 child bridge successfully
[16/07/2023, 18:04:08] Loaded 4 cached accessories from cachedAccessories.0EC8698B5622.
[16/07/2023, 18:04:08] [Hydrawise] Configuring Sprinkler from cache: Dopoutn
[16/07/2023, 18:04:08] [Hydrawise] Configuring Sprinkler from cache: Sakura
[16/07/2023, 18:04:08] [Hydrawise] Configuring Sprinkler from cache: Domeek
[16/07/2023, 18:04:08] [Hydrawise] Configuring Sprinkler from cache: Brna
[16/07/2023, 18:04:09] Homebridge v1.6.1 (HAP v0.11.1) (Hydrawise) is running on port 53045.

OK, but nothing happened on the garden, just:
[16/07/2023, 18:05:22] [Hydrawise] Received new running status for 'Sakura': on
[16/07/2023, 18:05:22] [Hydrawise] Received new remaining duration for 'Sakura': 775 seconds
[16/07/2023, 18:05:34] [Hydrawise] Received new remaining duration for 'Sakura': 763 seconds
[16/07/2023, 18:05:46] [Hydrawise] Received new remaining duration for 'Sakura': 751 seconds
[16/07/2023, 18:05:58] [Hydrawise] Received new remaining duration for 'Sakura': 739 seconds
[16/07/2023, 18:06:11] [Hydrawise] Received new remaining duration for 'Sakura': 727 seconds
[16/07/2023, 18:06:22] [Hydrawise] Received new remaining duration for 'Sakura': 715 seconds
[16/07/2023, 18:06:34] [Hydrawise] Received new remaining duration for 'Sakura': 703 seconds
[16/07/2023, 18:06:46] [Hydrawise] Received new remaining duration for 'Sakura': 691 seconds
[16/07/2023, 18:06:58] [Hydrawise] Received new remaining duration for 'Sakura': 679 seconds
[16/07/2023, 18:07:10] [Hydrawise] Received new remaining duration for 'Sakura': 667 seconds
[16/07/2023, 18:07:22] [Hydrawise] Received new remaining duration for 'Sakura': 655 seconds
[16/07/2023, 18:07:34] [Hydrawise] Received new remaining duration for 'Sakura': 643 seconds
[16/07/2023, 18:07:46] [Hydrawise] Received new remaining duration for 'Sakura': 631 seconds
[16/07/2023, 18:07:58] [Hydrawise] Received new remaining duration for 'Sakura': 619 seconds
[16/07/2023, 18:08:10] [Hydrawise] Received new remaining duration for 'Sakura': 607 seconds
[16/07/2023, 18:08:22] [Hydrawise] Received new remaining duration for 'Sakura': 595 seconds
[16/07/2023, 18:08:34] [Hydrawise] Received new remaining duration for 'Sakura': 583 seconds
[16/07/2023, 18:08:46] [Hydrawise] Received new remaining duration for 'Sakura': 571 seconds
[16/07/2023, 18:08:58] [Hydrawise] Received new remaining duration for 'Sakura': 559 seconds
[16/07/2023, 18:09:10] [Hydrawise] Received new remaining duration for 'Sakura': 547 seconds
[16/07/2023, 18:09:22] [Hydrawise] Received new remaining duration for 'Sakura': 535 seconds
[16/07/2023, 18:09:34] [Hydrawise] Received new remaining duration for 'Sakura': 523 seconds
[16/07/2023, 18:09:46] [Hydrawise] Received new remaining duration for 'Sakura': 511 seconds

**Comment by martijndierckx** [comment]
You are getting a 429 error. Meaning you’re requesting too often.

  1.  Disable the plugin for an hour
  2.  Lower the refresh timing
  3.  Reenable
  4.  Try again

________________________________
Van: Bodie2023 ***@***.***>
Verzonden: Sunday, July 16, 2023 6:10:37 PM
Aan: martijndierckx/homebridge-hydrawise ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [martijndierckx/homebridge-hydrawise] AxiosError: Request failed with status code 429 (Issue #36)


Hi there.
Until v3.0 I was operating under IP, now with v4.3 I switched to Cloud, but I am not able to start it. If I turn on Hydrawise from its native app, the change is written to both HB and HK/AH, but if I turn it on from HB or Apple Home, nothing happens except this listing.
Can you help me? Thanks for any advice.

[16/07/2023, 17:26:55] Homebridge v1.6.1 (HAP v0.11.1) (Hydrawise) is running on port 53045.
[16/07/2023, 17:26:56] [Hydrawise] AxiosError: Request failed with status code 429
at settle (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/axios/lib/core/settle.js:19:12)
at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/axios/lib/adapters/http.js:570:11)
at IncomingMessage.emit (node:events:525:35)
at endReadableNT (node:internal/streams/readable:1359:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21) {
code: 'ERR_BAD_REQUEST',
config: {
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},
adapter: [ 'xhr', 'http' ],
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
env: { FormData: [Function], Blob: [class Blob] },
validateStatus: [Function: validateStatus],
headers: AxiosHeaders {
Accept: 'application/json, text/plain, /',
'User-Agent': 'axios/1.4.0',
'Accept-Encoding': 'gzip, compress, deflate, br'
},
method: 'get',
url: 'https://app.hydrawise.com/api/v1/customerdetails.php',
params: { type: 'controllers', api_key: '6572-FD55-0D50-6846' },
json: true,
data: undefined
},
request: <ref *1> ClientRequest {
_events: [Object: null prototype] {
abort: [Function (anonymous)],
aborted: [Function (anonymous)],
connect: [Function (anonymous)],
error: [Function (anonymous)],
socket: [Function (anonymous)],
timeout: [Function (anonymous)],
finish: [Function: requestOnFinish]
},
_eventsCount: 7,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: false,
_last: true,
chunkedEncoding: false,
shouldKeepAlive: false,
maxRequestsOnConnectionReached: false,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: false,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
strictContentLength: false,
_contentLength: 0,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
_closed: false,
socket: TLSSocket {
_tlsOptions: [Object],
_secureEstablished: true,
_securePending: false,
_newSessionPending: false,
_controlReleased: true,
secureConnecting: false,
_SNICallback: null,
servername: 'app.hydrawise.com',
alpnProtocol: false,
authorized: true,
authorizationError: null,
encrypted: true,
_events: [Object: null prototype],
_eventsCount: 10,
connecting: false,
_hadError: false,
_parent: null,
_host: 'app.hydrawise.com',
_closeAfterHandlingError: false,
_readableState: [ReadableState],
_maxListeners: undefined,
_writableState: [WritableState],
allowHalfOpen: false,
_sockname: null,
_pendingData: null,
_pendingEncoding: '',
server: undefined,
_server: null,
ssl: [TLSWrap],
_requestCert: true,
_rejectUnauthorized: true,
parser: null,
_httpMessage: [Circular *1],
[Symbol(res)]: [TLSWrap],
[Symbol(verified)]: true,
[Symbol(pendingSession)]: null,
[Symbol(async_id_symbol)]: 36,
[Symbol(kHandle)]: [TLSWrap],
[Symbol(lastWriteQueueSize)]: 0,
[Symbol(timeout)]: null,
[Symbol(kBuffer)]: null,
[Symbol(kBufferCb)]: null,
[Symbol(kBufferGen)]: null,
[Symbol(kCapture)]: false,
[Symbol(kSetNoDelay)]: false,
[Symbol(kSetKeepAlive)]: true,
[Symbol(kSetKeepAliveInitialDelay)]: 60,
[Symbol(kBytesRead)]: 0,
[Symbol(kBytesWritten)]: 0,
[Symbol(connect-options)]: [Object]
},
_header: 'GET /api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846 HTTP/1.1\r\n' +
'Accept: application/json, text/plain, /\r\n' +
'User-Agent: axios/1.4.0\r\n' +
'Accept-Encoding: gzip, compress, deflate, br\r\n' +
'Host: app.hydrawise.com\r\n' +
'Connection: close\r\n' +
'\r\n',
_keepAliveTimeout: 0,
_onPendingData: [Function: nop],
agent: Agent {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object: null prototype],
requests: [Object: null prototype] {},
sockets: [Object: null prototype],
freeSockets: [Object: null prototype] {},
keepAliveMsecs: 1000,
keepAlive: false,
maxSockets: Infinity,
maxFreeSockets: 256,
scheduling: 'lifo',
maxTotalSockets: Infinity,
totalSocketCount: 1,
maxCachedSessions: 100,
_sessionCache: [Object],
[Symbol(kCapture)]: false
},
socketPath: undefined,
method: 'GET',
maxHeaderSize: undefined,
insecureHTTPParser: undefined,
joinDuplicateHeaders: undefined,
path: '/api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846',
_ended: true,
res: IncomingMessage {
_readableState: [ReadableState],
_events: [Object: null prototype],
_eventsCount: 4,
_maxListeners: undefined,
socket: [TLSSocket],
httpVersionMajor: 1,
httpVersionMinor: 1,
httpVersion: '1.1',
complete: true,
rawHeaders: [Array],
rawTrailers: [],
joinDuplicateHeaders: undefined,
aborted: false,
upgrade: false,
url: '',
method: null,
statusCode: 429,
statusMessage: 'Too Many Requests',
client: [TLSSocket],
_consuming: true,
_dumped: false,
req: [Circular *1],
responseUrl: 'https://app.hydrawise.com/api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846',
redirects: [],
[Symbol(kCapture)]: false,
[Symbol(kHeaders)]: [Object],
[Symbol(kHeadersCount)]: 10,
[Symbol(kTrailers)]: null,
[Symbol(kTrailersCount)]: 0
},
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
reusedSocket: false,
host: 'app.hydrawise.com',
protocol: 'https:',
_redirectable: Writable {
_writableState: [WritableState],
_events: [Object: null prototype],
_eventsCount: 3,
_maxListeners: undefined,
_options: [Object],
_ended: true,
_ending: true,
_redirectCount: 0,
_redirects: [],
_requestBodyLength: 0,
_requestBodyBuffers: [],
_onNativeResponse: [Function (anonymous)],
_currentRequest: [Circular *1],
_currentUrl: 'https://app.hydrawise.com/api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846',
[Symbol(kCapture)]: false
},
[Symbol(kCapture)]: false,
[Symbol(kBytesWritten)]: 0,
[Symbol(kEndCalled)]: true,
[Symbol(kNeedDrain)]: false,
[Symbol(corked)]: 0,
[Symbol(kOutHeaders)]: [Object: null prototype] {
accept: [Array],
'user-agent': [Array],
'accept-encoding': [Array],
host: [Array]
},
[Symbol(errored)]: null,
[Symbol(kUniqueHeaders)]: null
},
response: {
status: 429,
statusText: 'Too Many Requests',
headers: AxiosHeaders {
date: 'Sun, 16 Jul 2023 15:26:55 GMT',
'content-type': 'application/json; charset=utf-8',
'transfer-encoding': 'chunked',
connection: 'close',
server: 'nginx'
},
config: {
transitional: [Object],
adapter: [Array],
transformRequest: [Array],
transformResponse: [Array],
timeout: 0,
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
env: [Object],
validateStatus: [Function: validateStatus],
headers: [AxiosHeaders],
method: 'get',
url: 'https://app.hydrawise.com/api/v1/customerdetails.php',
params: [Object],
json: true,
data: undefined
},
request: <ref *1> ClientRequest {
_events: [Object: null prototype],
_eventsCount: 7,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: false,
_last: true,
chunkedEncoding: false,
shouldKeepAlive: false,
maxRequestsOnConnectionReached: false,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: false,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
strictContentLength: false,
_contentLength: 0,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
_closed: false,
socket: [TLSSocket],
_header: 'GET /api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846 HTTP/1.1\r\n' +
'Accept: application/json, text/plain, /\r\n' +
'User-Agent: axios/1.4.0\r\n' +
'Accept-Encoding: gzip, compress, deflate, br\r\n' +
'Host: app.hydrawise.com\r\n' +
'Connection: close\r\n' +
'\r\n',
_keepAliveTimeout: 0,
_onPendingData: [Function: nop],
agent: [Agent],
socketPath: undefined,
method: 'GET',
maxHeaderSize: undefined,
insecureHTTPParser: undefined,
joinDuplicateHeaders: undefined,
path: '/api/v1/customerdetails.php?type=controllers&api_key=6572-FD55-0D50-6846',
_ended: true,
res: [IncomingMessage],
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
reusedSocket: false,
host: 'app.hydrawise.com',
protocol: 'https:',
_redirectable: [Writable],
[Symbol(kCapture)]: false,
[Symbol(kBytesWritten)]: 0,
[Symbol(kEndCalled)]: true,
[Symbol(kNeedDrain)]: false,
[Symbol(corked)]: 0,
[Symbol(kOutHeaders)]: [Object: null prototype],
[Symbol(errored)]: null,
[Symbol(kUniqueHeaders)]: null
},
data: 'Exceeded maximum number of requests. You cannot make more than 5 requests in any 5 minute period to this endpoint.'

OK, I put 12000 to Pooling interval, restart and:

16/07/2023, 18:04:07] [Hydrawise] Restarting Process...
[16/07/2023, 18:04:08] [Hydrawise] Launched child bridge with PID 14784
[16/07/2023, 18:04:08] Registering platform 'homebridge-hydrawise.HydrawisePlatform'
[16/07/2023, 18:04:08] [Hydrawise] Loaded homebridge-hydrawise v1.2.1 child bridge successfully
[16/07/2023, 18:04:08] Loaded 4 cached accessories from cachedAccessories.0EC8698B5622.
[16/07/2023, 18:04:08] [Hydrawise] Configuring Sprinkler from cache: Dopoutn
[16/07/2023, 18:04:08] [Hydrawise] Configuring Sprinkler from cache: Sakura
[16/07/2023, 18:04:08] [Hydrawise] Configuring Sprinkler from cache: Domeek
[16/07/2023, 18:04:08] [Hydrawise] Configuring Sprinkler from cache: Brna
[16/07/2023, 18:04:09] Homebridge v1.6.1 (HAP v0.11.1) (Hydrawise) is running on port 53045.

OK, but nothing happened on the garden, just:
[16/07/2023, 18:05:22] [Hydrawise] Received new running status for 'Sakura': on
[16/07/2023, 18:05:22] [Hydrawise] Received new remaining duration for 'Sakura': 775 seconds
[16/07/2023, 18:05:34] [Hydrawise] Received new remaining duration for 'Sakura': 763 seconds
[16/07/2023, 18:05:46] [Hydrawise] Received new remaining duration for 'Sakura': 751 seconds
[16/07/2023, 18:05:58] [Hydrawise] Received new remaining duration for 'Sakura': 739 seconds
[16/07/2023, 18:06:11] [Hydrawise] Received new remaining duration for 'Sakura': 727 seconds
[16/07/2023, 18:06:22] [Hydrawise] Received new remaining duration for 'Sakura': 715 seconds
[16/07/2023, 18:06:34] [Hydrawise] Received new remaining duration for 'Sakura': 703 seconds
[16/07/2023, 18:06:46] [Hydrawise] Received new remaining duration for 'Sakura': 691 seconds
[16/07/2023, 18:06:58] [Hydrawise] Received new remaining duration for 'Sakura': 679 seconds
[16/07/2023, 18:07:10] [Hydrawise] Received new remaining duration for 'Sakura': 667 seconds
[16/07/2023, 18:07:22] [Hydrawise] Received new remaining duration for 'Sakura': 655 seconds
[16/07/2023, 18:07:34] [Hydrawise] Received new remaining duration for 'Sakura': 643 seconds
[16/07/2023, 18:07:46] [Hydrawise] Received new remaining duration for 'Sakura': 631 seconds
[16/07/2023, 18:07:58] [Hydrawise] Received new remaining duration for 'Sakura': 619 seconds
[16/07/2023, 18:08:10] [Hydrawise] Received new remaining duration for 'Sakura': 607 seconds
[16/07/2023, 18:08:22] [Hydrawise] Received new remaining duration for 'Sakura': 595 seconds
[16/07/2023, 18:08:34] [Hydrawise] Received new remaining duration for 'Sakura': 583 seconds
[16/07/2023, 18:08:46] [Hydrawise] Received new remaining duration for 'Sakura': 571 seconds
[16/07/2023, 18:08:58] [Hydrawise] Received new remaining duration for 'Sakura': 559 seconds
[16/07/2023, 18:09:10] [Hydrawise] Received new remaining duration for 'Sakura': 547 seconds
[16/07/2023, 18:09:22] [Hydrawise] Received new remaining duration for 'Sakura': 535 seconds
[16/07/2023, 18:09:34] [Hydrawise] Received new remaining duration for 'Sakura': 523 seconds
[16/07/2023, 18:09:46] [Hydrawise] Received new remaining duration for 'Sakura': 511 seconds

**Comment by richardmarr** [comment]
Getting the same 429 fyi - 'Exceeded maximum number of requests. You cannot make more than 10 requests in any 5 minute period to this endpoint.'

My calculation of the polling interval should be 5min*60sec*1000msec/10= 30000ms

Sound right?
