### ISSUE TITLE
Command Failed - git clone

### ISSUE THREAD

**Issue by joewilliamsca** [martijndierckx/homebridge-hydrawise#8]
Hi @martijndierckx   - when I tried to do an npm update on the new version of the home bridge-hydrawise plugin,   I'm getting the following error.

```
25 verbose stack Error: Command failed: git clone --mirror -q https://github.com
/jerrykeys/hydrawise-api.git /root/.npm/_cacache/tmp/git-clone-6e529f47/.git
25 verbose stack fatal: could not create leading directories of '/root/.npm/_cac
ache/tmp/git-clone-6e529f47/.git'
25 verbose stack
25 verbose stack     at ChildProcess.exithandler (child_process.js:303:12)
25 verbose stack     at ChildProcess.emit (events.js:315:20)
25 verbose stack     at maybeClose (internal/child_process.js:1026:16)
25 verbose stack     at Socket.<anonymous> (internal/child_process.js:441:11)
25 verbose stack     at Socket.emit (events.js:315:20)
25 verbose stack     at Pipe.<anonymous> (net.js:674:12)
```

Im still looking into it,  not sure if my NPM is the problem,  but if I find out what the problem is here,  I will post it

**Comment by W0GER** [comment]
When you run the npm command are you running that with sudo ? 

sudo npm -g update <packageName>

**Comment by joewilliamsca** [comment]
I tried with sudo,  and I just use root for all my home bridge setup...

Here is what's in my log file if you want to take a peek at it...

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'homebridge-hydrawise' ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose npm-session 0c910d9cba883b6c
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 304 https://registry.npmjs.org/homebridge-hydrawise 285ms (from cache)
9 silly pacote tag manifest for homebridge-hydrawise@latest fetched in 318ms
10 timing stage:loadCurrentTree Completed in 406ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule homebridge-hydrawise@0.0.5 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/promise 93ms (from cache)
19 silly pacote range manifest for promise@^7.0.4 fetched in 102ms
20 silly resolveWithNewModule promise@7.3.1 checking installable status
21 silly fetchPackageMetaData error for hydrawise-api@git+https://github.com/jerrykeys/hydrawise-api.git Command failed: git clone --mirror -q https://github.com/jerrykeys/hydrawise-api.git /root/.npm/_cacache/tmp/git-clone-ce178228/.git
21 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ce178228/.git'
22 timing stage:rollbackFailedOptional Completed in 1ms
23 timing stage:runTopLevelLifecycles Completed in 1301ms
24 silly saveTree root
24 silly saveTree `-- homebridge-hydrawise@0.0.5
24 silly saveTree   `-- promise@7.3.1
25 verbose stack Error: Command failed: git clone --mirror -q https://github.com/jerrykeys/hydrawise-api.git /root/.npm/_cacache/tmp/git-clone-ce178228/.git
25 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ce178228/.git'
25 verbose stack
25 verbose stack     at ChildProcess.exithandler (child_process.js:303:12)
25 verbose stack     at ChildProcess.emit (events.js:315:20)
25 verbose stack     at maybeClose (internal/child_process.js:1026:16)
25 verbose stack     at Socket.<anonymous> (internal/child_process.js:441:11)
25 verbose stack     at Socket.emit (events.js:315:20)
25 verbose stack     at Pipe.<anonymous> (net.js:674:12)
26 verbose cwd /root
27 verbose Linux 4.19.97-v7l+
28 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "homebridge-hydrawise"
29 verbose node v13.12.0
30 verbose npm  v6.14.4
31 error code 128
32 error Command failed: git clone --mirror -q https://github.com/jerrykeys/hydrawise-api.git /root/.npm/_cacache/tmp/git-clone-ce178228/.git
32 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ce178228/.git'
33 verbose exit [ 1, true ]

```

**Comment by joewilliamsca** [comment]
Found the issue,  it was a permission issue with my _cacache folder in NPM.
